name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  build:
    name: Build solution
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.1
      - name: Build
        run: msbuild Anwendungsentwicklung_WI17_Dre.sln /t:Build /p:Configuration=Release
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: Anwendungsentwicklung_WI17_Dre/bin/Release/
  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    name: Deploy to GitHub Releases
    needs: [ build ]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Prepare
        run: |
          mkdir -p staging/KursB_GenzRobin
          mkdir -p staging/Binaries
          rsync -r --exclude=artifacts --exclude=staging --exclude=.github --exclude=.gitignore --exclude=README.md ./* staging/KursB_GenzRobin
          mv artifacts/release/* staging/Binaries/
          cd staging && zip -r ../KursB_GenzRobin.zip KursB_GenzRobin && zip -r ../Binaries.zip Binaries
      - name: Deploy
        uses: softprops/action-gh-release@v1
        with:
          files: |
            KursB_GenzRobin.zip
            Binaries.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}